using System;
using System.Collections.Generic;

namespace TopDeskApiv2.TopDeskDatabase
{
    public partial class MutatieVestiging
    {
        public Guid Unid { get; set; }
        public Guid? Parentid { get; set; }
        public int MutStatus { get; set; }
        public DateTime? Datwijzig { get; set; }
        public Guid? Uidwijzig { get; set; }
        public decimal? MutAnnualdepreciation { get; set; }
        public Guid? MutAnnualdepreciationRid { get; set; }
        public bool MutAnnualdepreciationAct { get; set; }
        public Guid? MutBuildingLevelEpcId { get; set; }
        public Guid? MutBuildingLevelEpcIdRid { get; set; }
        public bool MutBuildingLevelEpcIdAct { get; set; }
        public int? MutDepreciationperiod { get; set; }
        public Guid? MutDepreciationperiodRid { get; set; }
        public bool MutDepreciationperiodAct { get; set; }
        public Guid? MutDesignationId { get; set; }
        public Guid? MutDesignationIdRid { get; set; }
        public bool MutDesignationIdAct { get; set; }
        public Guid? MutEnergyPerformanceId { get; set; }
        public Guid? MutEnergyPerformanceIdRid { get; set; }
        public bool MutEnergyPerformanceIdAct { get; set; }
        public DateTime? MutEnergyperformancemeasurementdate { get; set; }
        public Guid? MutEnergyperformancemeasurementdateRid { get; set; }
        public bool MutEnergyperformancemeasurementdateAct { get; set; }
        public Guid? MutEnvironmentalImpactId { get; set; }
        public Guid? MutEnvironmentalImpactIdRid { get; set; }
        public bool MutEnvironmentalImpactIdAct { get; set; }
        public DateTime? MutEnvironmentalimpactmeasurementdate { get; set; }
        public Guid? MutEnvironmentalimpactmeasurementdateRid { get; set; }
        public bool MutEnvironmentalimpactmeasurementdateAct { get; set; }
        public decimal? MutForeclosurevalue { get; set; }
        public Guid? MutForeclosurevalueRid { get; set; }
        public bool MutForeclosurevalueAct { get; set; }
        public DateTime? MutForeclosurevaluesurveydate { get; set; }
        public Guid? MutForeclosurevaluesurveydateRid { get; set; }
        public bool MutForeclosurevaluesurveydateAct { get; set; }
        public Guid? MutHistoricalSiteId { get; set; }
        public Guid? MutHistoricalSiteIdRid { get; set; }
        public bool MutHistoricalSiteIdAct { get; set; }
        public decimal? MutLandvalue { get; set; }
        public Guid? MutLandvalueRid { get; set; }
        public bool MutLandvalueAct { get; set; }
        public DateTime? MutLandvaluesurveydate { get; set; }
        public Guid? MutLandvaluesurveydateRid { get; set; }
        public bool MutLandvaluesurveydateAct { get; set; }
        public decimal? MutMarketvalue { get; set; }
        public Guid? MutMarketvalueRid { get; set; }
        public bool MutMarketvalueAct { get; set; }
        public DateTime? MutMarketvaluesurveydate { get; set; }
        public Guid? MutMarketvaluesurveydateRid { get; set; }
        public bool MutMarketvaluesurveydateAct { get; set; }
        public string MutOwneremail { get; set; }
        public Guid? MutOwneremailRid { get; set; }
        public bool MutOwneremailAct { get; set; }
        public string MutOwnermobilephone { get; set; }
        public Guid? MutOwnermobilephoneRid { get; set; }
        public bool MutOwnermobilephoneAct { get; set; }
        public string MutOwnername { get; set; }
        public Guid? MutOwnernameRid { get; set; }
        public bool MutOwnernameAct { get; set; }
        public string MutOwnertelephone { get; set; }
        public Guid? MutOwnertelephoneRid { get; set; }
        public bool MutOwnertelephoneAct { get; set; }
        public decimal? MutPriceofacquisition { get; set; }
        public Guid? MutPriceofacquisitionRid { get; set; }
        public bool MutPriceofacquisitionAct { get; set; }
        public decimal? MutPropertyvaluation { get; set; }
        public Guid? MutPropertyvaluationRid { get; set; }
        public bool MutPropertyvaluationAct { get; set; }
        public decimal? MutRebuildingvalue { get; set; }
        public Guid? MutRebuildingvalueRid { get; set; }
        public bool MutRebuildingvalueAct { get; set; }
        public DateTime? MutRebuildingvaluesurveydate { get; set; }
        public Guid? MutRebuildingvaluesurveydateRid { get; set; }
        public bool MutRebuildingvaluesurveydateAct { get; set; }
        public string MutRegistryreference { get; set; }
        public Guid? MutRegistryreferenceRid { get; set; }
        public bool MutRegistryreferenceAct { get; set; }
        public decimal? MutRentalvalue { get; set; }
        public Guid? MutRentalvalueRid { get; set; }
        public bool MutRentalvalueAct { get; set; }
        public DateTime? MutRentalvaluesurveydate { get; set; }
        public Guid? MutRentalvaluesurveydateRid { get; set; }
        public bool MutRentalvaluesurveydateAct { get; set; }
        public decimal? MutResidualvalue { get; set; }
        public Guid? MutResidualvalueRid { get; set; }
        public bool MutResidualvalueAct { get; set; }
        public double? MutSurfaceAreaM2 { get; set; }
        public Guid? MutSurfaceAreaM2Rid { get; set; }
        public bool MutSurfaceAreaM2Act { get; set; }
        public decimal? MutTotalcostofacquisition { get; set; }
        public Guid? MutTotalcostofacquisitionRid { get; set; }
        public bool MutTotalcostofacquisitionAct { get; set; }
        public double? MutVolumeM3 { get; set; }
        public Guid? MutVolumeM3Rid { get; set; }
        public bool MutVolumeM3Act { get; set; }
        public int? MutYearofacquisition { get; set; }
        public Guid? MutYearofacquisitionRid { get; set; }
        public bool MutYearofacquisitionAct { get; set; }
        public int? MutYearofconstruction { get; set; }
        public Guid? MutYearofconstructionRid { get; set; }
        public bool MutYearofconstructionAct { get; set; }
        public Guid? MutExtraaid { get; set; }
        public Guid? MutExtraaidRid { get; set; }
        public bool MutExtraaidAct { get; set; }
        public Guid? MutExtrabid { get; set; }
        public Guid? MutExtrabidRid { get; set; }
        public bool MutExtrabidAct { get; set; }
        public string Importid { get; set; }
        public int Importtype { get; set; }
        public DateTime? Importdate { get; set; }

        public Mutatiereden MutAnnualdepreciationR { get; set; }
        public BuildingLevelEpc MutBuildingLevelEpc { get; set; }
        public Mutatiereden MutBuildingLevelEpcIdR { get; set; }
        public Mutatiereden MutDepreciationperiodR { get; set; }
        public BranchDesignation MutDesignation { get; set; }
        public Mutatiereden MutDesignationIdR { get; set; }
        public EnergyPerformance MutEnergyPerformance { get; set; }
        public Mutatiereden MutEnergyPerformanceIdR { get; set; }
        public Mutatiereden MutEnergyperformancemeasurementdateR { get; set; }
        public EnvironmentalImpact MutEnvironmentalImpact { get; set; }
        public Mutatiereden MutEnvironmentalImpactIdR { get; set; }
        public Mutatiereden MutEnvironmentalimpactmeasurementdateR { get; set; }
        public Extraa MutExtraa { get; set; }
        public Mutatiereden MutExtraaidR { get; set; }
        public Extrab MutExtrab { get; set; }
        public Mutatiereden MutExtrabidR { get; set; }
        public Mutatiereden MutForeclosurevalueR { get; set; }
        public Mutatiereden MutForeclosurevaluesurveydateR { get; set; }
        public HistoricalSite MutHistoricalSite { get; set; }
        public Mutatiereden MutHistoricalSiteIdR { get; set; }
        public Mutatiereden MutLandvalueR { get; set; }
        public Mutatiereden MutLandvaluesurveydateR { get; set; }
        public Mutatiereden MutMarketvalueR { get; set; }
        public Mutatiereden MutMarketvaluesurveydateR { get; set; }
        public Mutatiereden MutOwneremailR { get; set; }
        public Mutatiereden MutOwnermobilephoneR { get; set; }
        public Mutatiereden MutOwnernameR { get; set; }
        public Mutatiereden MutOwnertelephoneR { get; set; }
        public Mutatiereden MutPriceofacquisitionR { get; set; }
        public Mutatiereden MutPropertyvaluationR { get; set; }
        public Mutatiereden MutRebuildingvalueR { get; set; }
        public Mutatiereden MutRebuildingvaluesurveydateR { get; set; }
        public Mutatiereden MutRegistryreferenceR { get; set; }
        public Mutatiereden MutRentalvalueR { get; set; }
        public Mutatiereden MutRentalvaluesurveydateR { get; set; }
        public Mutatiereden MutResidualvalueR { get; set; }
        public Mutatiereden MutSurfaceAreaM2R { get; set; }
        public Mutatiereden MutTotalcostofacquisitionR { get; set; }
        public Mutatiereden MutVolumeM3R { get; set; }
        public Mutatiereden MutYearofacquisitionR { get; set; }
        public Mutatiereden MutYearofconstructionR { get; set; }
        public Vestiging Parent { get; set; }
        public Gebruiker UidwijzigNavigation { get; set; }
    }
}
